services:
  meilisearch:
    image: getmeili/meilisearch
    container_name: meilisearch-engine
    environment:
      - MEILI_MASTER_KEY=REDACTED
      - MEILI_ENV=development
    ports:
      - "7700:7700"
    volumes:
      - meili_data:/data.ms
    networks:
      - hachimi-net

  backend:
    container_name: hachimi-viewer-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      # Spring Boot 数据库配置 (通过环境变量传入)
      - SPRING_DATASOURCE_URL=jdbc:mysql://host.docker.internal:3307/video_db?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=viewer
      - SPRING_DATASOURCE_PASSWORD=REDACTED
      # MEILI 变量
      - MEILI_HOST=http://meilisearch:7700
      - MEILI_API_KEY=REDACTED
      - MEILI_INDEX_VIDEOS=videos
    depends_on:
      - meilisearch
    networks:
      - hachimi-net
    # 添加 extra_hosts 来定义 host.docker.internal
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always

networks:
  hachimi-net:

volumes:
  meili_data: