services:
  backend:
    container_name: hachimi-viewer-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://mysql_video_db:3306/video_db?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    networks:
      - hachimi-net
      - mysql-external-net

networks:
  hachimi-net:
  mysql-external-net:
    external: true
    name: mysql_server_default
